const APP_STATIONS_TABLE = "stations";
const APP_JOURNEYS_TABLE = "journeys";
const APP_JOURNEYS_TABLE_STRING_COLUMNS =
	"departure_date::text return_date::text departure_station_name return_station_name";
const APP_JOURNEYS_TABLE_NUMBER_COLUMNS =
	"departure_station_id return_station_id covered_distance duration";
const APP_STATIONS_TABLE_STRING_COLUMNS = "name address city operator";
const APP_STATIONS_TABLE_NUMBER_COLUMNS = "id capacity x y";

enum STATIONS_ENDPOINT_DIRECTION_START {
	FROM_STATION = "departure",
}

const QUERY_NUMBER_EQUALITY_TOLERANCE = 0.01;

export {
	APP_STATIONS_TABLE,
	APP_JOURNEYS_TABLE,
	APP_JOURNEYS_TABLE_STRING_COLUMNS,
	APP_JOURNEYS_TABLE_NUMBER_COLUMNS,
	APP_STATIONS_TABLE_STRING_COLUMNS,
	APP_STATIONS_TABLE_NUMBER_COLUMNS,
	STATIONS_ENDPOINT_DIRECTION_START,
	QUERY_NUMBER_EQUALITY_TOLERANCE,
};
